### ISSUE TITLE
Entrega Trabajo Práctico Nº 1

### ISSUE THREAD

**Issue by Facupitta** [EmanuelPrima/2020_K2002_Grupo_5#1]
Solicito corrección del trabajo práctico: @santiagoferreiros

**Comment by santiagoferreiros** [comment]
@Facupitta @EmanuelPrima @milegarro @arielmarin @TBarbierii 

Estimados

Excelente trabajo. Muy claro, sin rebuscarse en el código.

Lo único

int procesarCaracter (char c, int automata[7][5],int estado)

A esa función, le pasan el caracter y el automata como parámetro y no lo utiliza ! Solo usa el estado.

Nota 9

Felicitaciones =)

A seguir así !!!
