### ISSUE TITLE
Entrega Trabajo Práctico Nº2

### ISSUE THREAD

**Issue by Facupitta** [EmanuelPrima/2020_K2002_Grupo_5#2]
Solicitamos corrección del trabajo práctico: @santiagoferreiros

**Comment by santiagoferreiros** [comment]
Estimados,

Buen trabajo !
No hay implementado una pila como tal. Para eso deben utilizar punteros. Pero veo que no son los únicos, lo voy a explicar en clase para todos.

El TP cumple la funcionalidad y está aprobado.

Nota: 7

@Facupitta @EmanuelPrima @milegarro @arielmarin
