### ISSUE TITLE
Entrega Trabajo Práctico Nº 3

### ISSUE THREAD

**Issue by Facupitta** [EmanuelPrima/2020_K2002_Grupo_5#3]
Solicito corrección del trabajo práctico @santiagoferreiros

**Comment by santiagoferreiros** [comment]
Equipo

Muy buen trabajo

![image](https://user-images.githubusercontent.com/46604718/88960509-ffa37680-d279-11ea-90db-a964a562ef9b.png)

Hay algunos caracteres de puntuación que contó demás, creo que puede ser los espacios o las tabulaciones.

Según puedo ver, la ERX de literales cadena no permite esto por ejemplo " Hola \"Mundo\" "

Lo podrían revisar para el tp integrador,
La entrega está muy bien,
Nota 9

Saludos,

Santiago
