### ISSUE TITLE
Entrega Trabajo Práctico Nº 4

### ISSUE THREAD

**Issue by TBarbierii** [EmanuelPrima/2020_K2002_Grupo_5#4]
Solicito corrección del trabajo práctico @santiagoferreiros

**Comment by santiagoferreiros** [comment]
Estimados,

Han realizado un excelente trabajo.
Muy prolijo todo. 
Espero que sigan con este ritmo y tipo de entrega en el trabajo integrador.
Adelante que ustedes pueden, vamos por más :)

Nota: 10

Saludos,

Santiago
